// SPDX-FileCopyrightText: Copyright (c) Stanford University, The Regents of the
// University of California, and others. SPDX-License-Identifier: BSD-3-Clause

#include "ChamberSphere.h"

#include "Model.h"

void ChamberSphere::setup_dofs(DOFHandler& dofhandler) {
  Block::setup_dofs_(dofhandler, 5,
                     {"stress", "tau", "volume"});
}

void ChamberSphere::update_constant(SparseSystem& system,
                                    std::vector<double>& parameters) {
  system.E.coeffRef(global_eqn_ids[2], global_var_ids[5]) = 1;
  system.E.coeffRef(global_eqn_ids[3], global_var_ids[6]) = -1;
  system.F.coeffRef(global_eqn_ids[0], global_var_ids[2]) = -1;
  system.F.coeffRef(global_eqn_ids[0], global_var_ids[4]) = 1;
  system.F.coeffRef(global_eqn_ids[1], global_var_ids[4]) = -1;
  system.F.coeffRef(global_eqn_ids[1], global_var_ids[5]) = 1;
  system.F.coeffRef(global_eqn_ids[3], global_var_ids[1]) = 1;
  system.F.coeffRef(global_eqn_ids[3], global_var_ids[3]) = -1;
  system.F.coeffRef(global_eqn_ids[4], global_var_ids[0]) = 1;
  system.F.coeffRef(global_eqn_ids[4], global_var_ids[2]) = -1;
}

void ChamberSphere::update_time(SparseSystem& system,
                                std::vector<double>& parameters) {
  const double gamma_sigma_max = parameters[global_param_ids[ParamId::gamma_sigma_max]];

  // active stress
  get_elastance_values(parameters);
  system.F.coeffRef(global_eqn_ids[2], global_var_ids[5]) = act;
  system.C.coeffRef(global_eqn_ids[2]) = -act_plus*gamma_sigma_max;
}

void ChamberSphere::update_solution(
    SparseSystem& system, std::vector<double>& parameters,
    const Eigen::Matrix<double, Eigen::Dynamic, 1>& y,
    const Eigen::Matrix<double, Eigen::Dynamic, 1>& dy) {
  const double prestress = parameters[global_param_ids[ParamId::prestress]];
  const double volume0 = parameters[global_param_ids[ParamId::volume0]];
  const double gamma_W1 = parameters[global_param_ids[ParamId::gamma_W1]];
  const double Pout = y[global_var_ids[2]];
  const double stress = y[global_var_ids[4]];
  const double volume = y[global_var_ids[6]];
  system.C.coeffRef(global_eqn_ids[0]) = -Pout*pow((volume + volume0)/volume0, 0.66666666666666663) + Pout + stress*pow((volume + volume0)/volume0, 0.33333333333333331) - stress;
  system.C.coeffRef(global_eqn_ids[1]) = -4*gamma_W1*pow(volume/volume0 + 1, -2.0) + 4*gamma_W1 + prestress;
  system.dC_dy.coeffRef(global_eqn_ids[0], global_var_ids[2]) = 1 - pow((volume + volume0)/volume0, 0.66666666666666663);
  system.dC_dy.coeffRef(global_eqn_ids[0], global_var_ids[4]) = pow((volume + volume0)/volume0, 0.33333333333333331) - 1;
  system.dC_dy.coeffRef(global_eqn_ids[0], global_var_ids[6]) = (-0.66666666666666663*Pout*pow((volume + volume0)/volume0, 0.66666666666666663) + 0.33333333333333331*stress*pow((volume + volume0)/volume0, 0.33333333333333331))/(volume + volume0);
  system.dC_dy.coeffRef(global_eqn_ids[1], global_var_ids[6]) = 8.0*gamma_W1*pow((volume + volume0)/volume0, -3.0)/volume0;
}

void ChamberSphere::get_elastance_values(std::vector<double>& parameters) {
  const double alpha_max = parameters[global_param_ids[ParamId::alpha_max]];
  const double alpha_min = parameters[global_param_ids[ParamId::alpha_min]];
  const double tsys = parameters[global_param_ids[ParamId::tsys]];
  const double tdias = parameters[global_param_ids[ParamId::tdias]];
  const double steepness = parameters[global_param_ids[ParamId::steepness]];

  const double t = model->time;

  const auto T_cardiac = model->cardiac_cycle_period;
  const auto t_in_cycle = fmod(model->time, T_cardiac);

  const double S_plus = 0.5 * (1.0 + tanh((t_in_cycle - tsys) / steepness));
  const double S_minus = 0.5 * (1.0 - tanh((t_in_cycle - tdias) / steepness));

  // indicator function
  const double f = S_plus * S_minus;

  // activation rates
  const double act_t = alpha_max * f + alpha_min * (1 - f);

  act = std::abs(act_t);
  act_plus = std::max(act_t, 0.0);
}

void ChamberSphere::update_gradient(
    Eigen::SparseMatrix<double>& jacobian,
    Eigen::Matrix<double, Eigen::Dynamic, 1>& residual,
    Eigen::Matrix<double, Eigen::Dynamic, 1>& alpha, std::vector<double>& y,
    std::vector<double>& dy) {
  // Calibrates the chamber parameters from a full-state observation set. The
  // time-independent parameters (volume0, gamma_W1, prestress) appear in the
  // momentum and spherical-stress equations; the active-stress equation (eq 2)
  // and its parameters (gamma_sigma_max and the activation timing) depend on the
  // observation time, which the optimizer supplies via model->time when a time
  // vector is given. Shared subexpressions are hoisted into temporaries (xN).
  // Generated by scripts/jacobian.py from scripts/ChamberSphere.yaml.
  const double volume0 = alpha[global_param_ids[ParamId::volume0]];
  const double gamma_W1 = alpha[global_param_ids[ParamId::gamma_W1]];
  const double gamma_sigma_max = alpha[global_param_ids[ParamId::gamma_sigma_max]];
  const double prestress = alpha[global_param_ids[ParamId::prestress]];
  const double alpha_max = alpha[global_param_ids[ParamId::alpha_max]];
  const double alpha_min = alpha[global_param_ids[ParamId::alpha_min]];
  const double tsys = alpha[global_param_ids[ParamId::tsys]];
  const double tdias = alpha[global_param_ids[ParamId::tdias]];
  const double steepness = alpha[global_param_ids[ParamId::steepness]];
  const double Pin = y[global_var_ids[0]];
  const double Qin = y[global_var_ids[1]];
  const double Pout = y[global_var_ids[2]];
  const double Qout = y[global_var_ids[3]];
  const double stress = y[global_var_ids[4]];
  const double tau = y[global_var_ids[5]];
  const double volume = y[global_var_ids[6]];
  const double dtau_dt = dy[global_var_ids[5]];
  const double dvolume_dt = dy[global_var_ids[6]];
  const double t = model->cardiac_cycle_period > 0.0 ? fmod(model->time, model->cardiac_cycle_period) : model->time;

  const double x0 = 1.0/volume0;
  const double x1 = volume + volume0;
  const double x2 = x0*x1;
  const double x3 = Pout*pow(x2, 0.66666666666666663);
  const double x4 = pow(x2, 0.33333333333333331);
  const double x5 = pow(x2, -2.0);
  const double x6 = 1.0/steepness;
  const double x7 = t - tdias;
  const double x8 = tanh(x6*x7);
  const double x9 = 0.5*x8 - 0.5;
  const double x10 = t - tsys;
  const double x11 = tanh(x10*x6);
  const double x12 = 0.5*x11 + 0.5;
  const double x13 = x12*x9;
  const double x14 = x13 + 1;
  const double x15 = alpha_max*x13 - alpha_min*x14;
  const double x16 = -x9;
  const double x17 = x12*x16;
  const double x18 = 1 - x17;
  const double x19 = alpha_max*x17 + alpha_min*x18;
  const double x20 = fmax(0, x19);
  const double x21 = volume*x0;
  const double x22 = x21/x1;
  const double x23 = gamma_sigma_max*(x19 > 0 ? 1.0 : 0.0);
  const double x24 = (((x15) > 0) - ((x15) < 0));
  const double x25 = 1 - pow(x11, 2);
  const double x26 = 0.5*x6;
  const double x27 = x25*x26;
  const double x28 = 1 - pow(x8, 2);
  const double x29 = x12*x28;
  const double x30 = alpha_max*x26*x29 - 0.5*alpha_min*x12*x28*x6;
  const double x31 = 0.5/pow(steepness, 2);
  const double x32 = x10*x25*x31;
  const double x33 = x16*x32;
  const double x34 = x29*x31*x7;
  const double x35 = alpha_max*x34;
  const double x36 = x32*x9;

  residual(global_eqn_ids[0]) = stress*x4 - x3;
  residual(global_eqn_ids[1]) = 4*gamma_W1*(1 - x5) + prestress - stress + tau;
  residual(global_eqn_ids[2]) = dtau_dt - gamma_sigma_max*x20 + tau*fabs(x15);
  residual(global_eqn_ids[3]) = Qin - Qout - dvolume_dt;
  residual(global_eqn_ids[4]) = Pin - Pout;
  jacobian.coeffRef(global_eqn_ids[0], global_param_ids[ParamId::volume0]) = x22*(-0.33333333333333331*stress*x4 + 0.66666666666666663*x3);
  jacobian.coeffRef(global_eqn_ids[1], global_param_ids[ParamId::volume0]) = -8.0*gamma_W1*x22*x5;
  jacobian.coeffRef(global_eqn_ids[1], global_param_ids[ParamId::gamma_W1]) = 4 - 4*pow(x21 + 1, -2.0);
  jacobian.coeffRef(global_eqn_ids[2], global_param_ids[ParamId::gamma_sigma_max]) = -x20;
  jacobian.coeffRef(global_eqn_ids[1], global_param_ids[ParamId::prestress]) = 1;
  jacobian.coeffRef(global_eqn_ids[2], global_param_ids[ParamId::alpha_max]) = tau*x12*x24*x9 - x17*x23;
  jacobian.coeffRef(global_eqn_ids[2], global_param_ids[ParamId::alpha_min]) = -tau*x14*x24 - x18*x23;
  jacobian.coeffRef(global_eqn_ids[2], global_param_ids[ParamId::tsys]) = tau*x24*(-alpha_max*x27*x9 + 0.5*alpha_min*x25*x6*x9) - x23*(-alpha_max*x16*x27 + 0.5*alpha_min*x16*x25*x6);
  jacobian.coeffRef(global_eqn_ids[2], global_param_ids[ParamId::tdias]) = -tau*x24*x30 - x23*x30;
  jacobian.coeffRef(global_eqn_ids[2], global_param_ids[ParamId::steepness]) = tau*x24*(-alpha_max*x36 - alpha_min*(-x34 - x36) - x35) - x23*(-alpha_max*x33 + alpha_min*(x33 - x34) + x35);
}